apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
  namespace: crossplane-system
  labels:
    app.kubernetes.io/name: provider-helm
    app.kubernetes.io/component: provider
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.19.0
  packagePullPolicy: IfNotPresent
  runtimeConfigRef:
    name: provider-runtime-config
