apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provider-helm-namespace-creator
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "create", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-helm-namespace-creator-binding
subjects:
- kind: ServiceAccount
  name: provider-helm-503c3591121b
  namespace: crossplane-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: provider-helm-namespace-creator
